### ISSUE TITLE
Incremental compilation support (Gradle)

### ISSUE THREAD

**Issue by ben-manes** [h908714124/auto-builder#14]
I think this might be as easy as updating the manifest, but not sure.
https://docs.gradle.org/4.7/userguide/java_plugin.html#sec:incremental_annotation_processing

**Comment by h908714124** [comment]
I think this is already an incremental processor, so should be compatible. But I will also check with an actual gradle 5.

**Comment by h908714124** [comment]
Marking the processor as aggregating may or may not be necessary, but it should be safer since we're looking at the class that's generated by auto-value, which may violate one rule of "isolating" annotation processing.

I've added [this file](https://github.com/h908714124/auto-builder/blob/master/core/src/main/resources/META-INF/gradle/incremental.annotation.processors) to mark it as aggregating.

Thanks for the hint!
