### ISSUE TITLE
Improved Collections handling

### ISSUE THREAD

**Issue by ben-manes** [h908714124/auto-builder#3]
It would be nice if the builder generated helper methods to match the idioms of hand built ones. See the [documentation](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#-use-a-collection-valued-property) for all of the collection goodness. This would be for collections and maps.

This would improve...
 - how values are accumulated
 - have support for ImmutableXXX types
 - defaulting to an empty collection (no setting required)

**Comment by h908714124** [comment]
I like this idea, especially the defaulting to an empty collection. Support for `ImmutableXXX` would be also be very nice, because there's currently no standard alternative for guava's immutable collections.

I'm not an active auto-value user myself. Unfortunately it's not a priority where I work. So I did an experiment, see below. To my surprise, auto-value doesn't seem support the defaulting to an empty collection:

````java
@AutoValue
abstract class FuguFish {
  abstract List<String> friends();

  @AutoValue.Builder
  static abstract class Builder {
    abstract Builder friends(List<String> name);
    abstract FuguFish build();
  }
}
````

Then `new AutoValue_FuguFish.Builder().build()` throws a

> java.lang.IllegalStateException: Missing required properties: friends

If it turns out that auto-value really doesn't support this defaulting, then that doesn't mean that it can't be added to auto-builder. It's probably very convenient, and in fact it's similar to the `Optional.empty` logic that's already there. However, there's many different collections, so there should be a simple rule which ones exactly are supported.

Lastly, I believe the main use case for the defaulting is to _create_ an instances, rather than _updating_ it. So may I suggest that you also have a look at [crate](https://github.com/h908714124/crate) for this purpose, if you don't mind the performance hit of creating an extra object for each step. It's possible that crate would be a more suitable place for the collection defaulting functionality, especially if we want to keep auto-builder as close as possible to auto-builder. Also, it's probably easier for maintainers to add convenience methods there, since each step is a separate object, so there's less risk of a naming collision.

**Comment by h908714124** [comment]
I understand now, you'd have to implement the _defaulting to empty_ manually, in `FuguFish.Builder`. I hope get something done soon, at least for `util.List`, `util.Map`, `util.Set` and their guava analogues.

**Comment by ben-manes** [comment]
For a Map it does default to an empty collection, but perhaps the rules need to be investigated. A case that I didn't convert over looks like,

```java
Builder {
  abstract ImmutableMap.Builder<UUID, Path> filesBuilder();
  ...
}
...
build() {
  if (filesBuilder$ != null) {
    this.files = filesBuilder$.build();
  } else if (this.files == null) {
    this.files = ImmutableMap.of();
  }
  ...
}
```

**Comment by h908714124** [comment]
Yup, that's pretty verbose too. I've just tentatively released version 2.0 (no special meaning in the number, just incrementing by 0.1). This prevents NPE for 6 common collections. See [here](https://github.com/h908714124/auto-builder/blob/master/core/src/main/java/net/autobuilder/core/Collectionish.java) for implementation details. The `Collectionish` class should be easy to extend, if these 6 are not enough.

This improvement should take care of all but the first suggestion. If I don't get any complaints, I'll close this ticket in a few days. In that case, you're welcome to open another one, if you also need the accumulator.

**Comment by ben-manes** [comment]
The `build()` method was auto-generated by `AutoValue.Builder`, if that wasn't clear.

I do need the accumulator and it would be nice if all the options in the `AutoValue` documentation were generated. This was what prompted me to open a ticket, since the rest are more superficial.

fyi, you can increment into double digits, e.g. `1.12`, in a semantic versioning style (major, minor, patch). But that's just a style.

**Comment by h908714124** [comment]
`2.1` adds aggregation support for guava types. See [here](https://github.com/h908714124/auto-builder/blob/master/examples/src/test/java/net/autobuilder/examples/BirdTest.java). So far, only the guava types `ImmutableList`, `ImmutableSet` and `ImmutableMap` can do aggregation.

* The aggregator method name is `addFeet` etc, which can be confusing because this adds one foot. If this gets too annoying, we can try chopping an `s` off the end or something (but that would only work for English, so I'm not too enthusiastic).
* The setter and aggregator can be called in any order. According to the docs, that would be `RuntimeException` in auto-value. Here, the setter just sets, regardless of what happened before, and the aggregator always appends, regardless of what happened before. Yes, the aggregator state is lost when the setter is called, but that's just how setters work.
* If there's a risk of naming conflict (see [Bird.Nest](https://github.com/h908714124/auto-builder/blob/master/examples/src/main/java/net/autobuilder/examples/Bird.java), then no aggregator is generated.

**Comment by h908714124** [comment]
How about `addTo*` as the aggregator name? `addToFeet` makes more sense than `addFeet`. `putIn*` could be used for maps.

**Comment by h908714124** [comment]
OK done that, `2.2` is released and uses `addTo` and `putIn` for the aggregator method name. I reconsidered and thought that `addTo` for maps would be too confusing.
If you agree that the original points are all addressed now, I'll close this issue in a day or so.

**Comment by ben-manes** [comment]
That sounds great, thanks!

**Comment by ben-manes** [comment]
A small improvement would be to make the Immutable setters more generic. For example,

```java
class X {
  ImmutableMap<A, B> map();
}

Builder {
  Builder map(ImmutableMap<A, B> map);
}
```

Instead accept a `Map` and use `ImmutableMap.copyOf(map)`, which will no-op if an immutable parameter.

**Comment by h908714124** [comment]
That should also work now, with release `2.3`.
